### ISSUE TITLE
Failed to activate the quotes package

### ISSUE THREAD

**Issue by seoker** [hemanth/atom-quotes#4]
[Enter steps to reproduce below:]
1. Install the package.
2. Select a text and press ctrl-shift-6

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [quotes](https://github.com/hemanth/atom-quotes) package, v0.1.0
### Stack Trace

Failed to activate the quotes package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/seokerwang/.atom/packages/quotes/lib/quotes.coffee:8:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -6:48.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -6:48.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -6:48.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:48.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -6:48 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -6:48 snippets:expand (atom-text-editor.editor.is-focused)
     -6:48 editor:indent (atom-text-editor.editor.is-focused)
  3x -6:47 core:move-right (atom-text-editor.editor.is-focused)
     -6:46.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -6:43.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:31.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:08.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:06.0 aligner:align (atom-text-editor.editor.is-focused)
     -4:01.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:05.5.0 pane:show-item-6 (atom-text-editor.editor.is-focused)
  2x -0:08.4.0 Quotes:quote (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
aligner, v0.13.0
api-docs, v0.0.3
atom-beautify, v0.28.7
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.10
jshint, v1.3.9
linter-eslint, v2.4.3
linter-js-standard, v1.2.0
merge-conflicts, v1.3.2
quotes, v0.1.0

# Dev
No dev packages
```

**Comment by ccschmitz** [comment]
I've been hitting this again since the 1.1.0 update.

**Comment by hemanth** [comment]
:| need to look into this.

**Comment by ghost** [comment]
I was so excited for this 8( lol; hope it gets working soon. Good luck 8)

**Comment by ghost** [comment]
Turns out atom-quoter does the trick
